package com.sprint.core_api.entity;

import com.sprint.core_api.enums.Severity;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.Instant;
import java.util.UUID;

@Entity
@Table(name = "alerts")
@Getter
@Setter
@NoArgsConstructor
public class Alert {
    @Id
    private UUID id; // Generated by Analyzer, so we just read it

    @Column(name = "rule_name")
    private String ruleName;

    @Enumerated(EnumType.STRING)
    private Severity severity;

    private String username;

    @Column(name = "source_ip")
    private String sourceIp;

    @Column(name = "triggered_at")
    private Instant triggeredAt;

    @Column(columnDefinition = "TEXT")
    private String details;
}